### ISSUE TITLE
Configurable HTTP proxy

### ISSUE THREAD

**Issue by mccarths** [twilio/authy-devise#106]
Is it/would it be possible to configure this gem to make HTTP calls via a proxy? Possibly via an extra configuration item:
```
Authy.http_proxy = 'http://myproxy:8080'
```
Then included in the call to `IncludeClient` in `api.rb` or something similar:
```
include_http_client(Authy.http_proxy, ...
```

**Comment by philnash** [comment]
This looks like something that would need to be added to [`authy-ruby`](https://github.com/twilio/authy-ruby/). In fact, this library just straight uses the config for `authy-ruby`, so it might not even need a change in `authy-devise`.  I would open [an issue in `authy-ruby`](https://github.com/twilio/authy-ruby/issues) and see whether it can get changed there first.

**Comment by mccarths** [comment]
oh yeah I see, my bad, will try it out there. Thanks!
