### ISSUE TITLE
"Log In" routes disappeared and Devise is now throwing errors everywhere

### ISSUE THREAD

**Issue by JacobCZ** [twilio/authy-devise#107]
I installed the gem, followed all the steps in the guide (using the generator) and now my "Log In" route in devise is gone and I'm getting a NoMethodError in Devise::Registrations#new because of Devise's _app/views/devise/shared/_links.html.erb_ file, telling me that the path  ```new_session_path(resource_name)``` does not exist...

I have not changed anything manually and simply ran the generators and migrations.

Ruby version 2.5.3
Rails version 5.2.1
Devise version 4.5.0
Devise-Authy version: 1.10.0

**Comment by philnash** [comment]
That's odd! What does your `config/routes.rb` look like now? And what do you get when you run `rails routes`?

**Comment by philnash** [comment]
Hey, this issue is kind of old and I never got a response, so hopefully it all worked out for you.

I'm going to close it, but if you still need help, please re-open it.
