### ISSUE TITLE
Breaks password authentication in Rails 5.2/Devise 4.5?

### ISSUE THREAD

**Issue by alexford** [twilio/authy-devise#109]
Installing the gem and following the setup instructions (and doing nothing else) in a Rails 5.2 setup results in `ActionController::InvalidAuthenticityToken` errors when logging in via password.

This issue was reported as #91 by someone else and confirmed by a third, but his resolution wasn't posted. This seems like a bug as there are no version requirements in the README or indications that this shouldn't work.

It's totally possible I'm totally off-base and both I and the original reporter have something odd in our setups! If it's determined to not be a bug in this repo, I think a README update to indicate compatibility or whatever gotcha we've run into is in order.

I notice the Rails app used in the tests is version 4.2.7, with devise 3.0.0, which is pretty far behind obviously.

### Theory (only somewhat tested and not fully understood)

The calls to `signed_in?`in `Controllers::Helpers` referenced in #76 (here: https://github.com/twilio/authy-devise/blob/master/lib/devise-authy/controllers/helpers.rb#L43), are causing the CSRF token to clear, since that method (from Devise) runs callback hooks, one of which is presumably clearing the token. I've confirmed that `session['_csrf_token']` changes to nil when `signed_in?` is run. Later in the stack, the requests's CSRF token gets checked again  which raises the authenticity token error. 

Removing the `before_filter` for `check_request_and_redirect_to_verify_token` in that Helper gets around this issue but cripples the gem of course.

I think it's possible that perhaps something's changed in the `before_filter` order that makes this call to `signed_in?` the first for the request, whereas before Warden would have already done its thing?

I tried replacing `signed_in?` with `warden.authenticate?` as suggested in Devise's source comments, and that returns `false` as I'm signing in (`signed_in?` returns true of course, but it also actually triggers the sign in), which I think supports the idea that the `before_action` is being called at a different stage in the process now.

Rails 5 apparently changed the order for `protect_from_forgery`: https://blog.bigbinary.com/2016/04/06/rails-5-default-protect-from-forgery-prepend-false.html. I tried also setting `protect_from_forgery with: :exception, prepend: true` in my ApplicationController ~~but that did not work. For some reason the filter in the authy-devise helper still seems to run first.~~ EDIT: See comments—this was the resolution needed

`signed_in?` and its comments are in Devise here: https://github.com/plataformatec/devise/blob/715192a7709a4c02127afb067e66230061b82cf2/lib/devise/controllers/sign_in_out.rb#L13

### Environment

Ruby 2.6.0
Rails 5.2.2
Devise 4.5.0
Puma, though I see the same problem in a single-threaded server like WEBrick
Development environment

### Trace

```
actionpack (5.2.2) lib/action_controller/metal/request_forgery_protection.rb:211:in `handle_unverified_request'
actionpack (5.2.2) lib/action_controller/metal/request_forgery_protection.rb:243:in `handle_unverified_request'
devise (4.5.0) lib/devise/controllers/helpers.rb:255:in `handle_unverified_request'
actionpack (5.2.2) lib/action_controller/metal/request_forgery_protection.rb:238:in `verify_authenticity_token'
activesupport (5.2.2) lib/active_support/callbacks.rb:426:in `block in make_lambda'
activesupport (5.2.2) lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
actionpack (5.2.2) lib/abstract_controller/callbacks.rb:34:in `block (2 levels) in <module:Callbacks>'
activesupport (5.2.2) lib/active_support/callbacks.rb:199:in `block in halting'
activesupport (5.2.2) lib/active_support/callbacks.rb:513:in `block in invoke_before'
activesupport (5.2.2) lib/active_support/callbacks.rb:513:in `each'
activesupport (5.2.2) lib/active_support/callbacks.rb:513:in `invoke_before'
activesupport (5.2.2) lib/active_support/callbacks.rb:107:in `block in run_callbacks'
sentry-raven (2.7.4) lib/raven/integrations/rails/controller_transaction.rb:7:in `block in included'
activesupport (5.2.2) lib/active_support/callbacks.rb:118:in `instance_exec'
activesupport (5.2.2) lib/active_support/callbacks.rb:118:in `block in run_callbacks'
audited (4.8.0) lib/audited/sweeper.rb:14:in `around'
activesupport (5.2.2) lib/active_support/callbacks.rb:118:in `block in run_callbacks'
audited (4.8.0) lib/audited/sweeper.rb:14:in `around'
activesupport (5.2.2) lib/active_support/callbacks.rb:118:in `block in run_callbacks'
activesupport (5.2.2) lib/active_support/callbacks.rb:136:in `run_callbacks'
actionpack (5.2.2) lib/abstract_controller/callbacks.rb:41:in `process_action'
actionpack (5.2.2) lib/action_controller/metal/rescue.rb:22:in `process_action'
actionpack (5.2.2) lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
activesupport (5.2.2) lib/active_support/notifications.rb:168:in `block in instrument'
activesupport (5.2.2) lib/active_support/notifications/instrumenter.rb:23:in `instrument'
activesupport (5.2.2) lib/active_support/notifications.rb:168:in `instrument'
actionpack (5.2.2) lib/action_controller/metal/instrumentation.rb:32:in `process_action'
actionpack (5.2.2) lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
activerecord (5.2.2) lib/active_record/railties/controller_runtime.rb:24:in `process_action'
actionpack (5.2.2) lib/abstract_controller/base.rb:134:in `process'
actionview (5.2.2) lib/action_view/rendering.rb:32:in `process'
actionpack (5.2.2) lib/action_controller/metal.rb:191:in `dispatch'
actionpack (5.2.2) lib/action_controller/metal.rb:252:in `dispatch'
actionpack (5.2.2) lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
actionpack (5.2.2) lib/action_dispatch/routing/route_set.rb:34:in `serve'
actionpack (5.2.2) lib/action_dispatch/routing/mapper.rb:18:in `block in <class:Constraints>'
actionpack (5.2.2) lib/action_dispatch/routing/mapper.rb:48:in `serve'
actionpack (5.2.2) lib/action_dispatch/journey/router.rb:52:in `block in serve'
actionpack (5.2.2) lib/action_dispatch/journey/router.rb:35:in `each'
actionpack (5.2.2) lib/action_dispatch/journey/router.rb:35:in `serve'
actionpack (5.2.2) lib/action_dispatch/routing/route_set.rb:840:in `call'
rack-pjax (1.0.0) lib/rack/pjax.rb:12:in `call'
twilio-ruby (5.18.0) lib/rack/twilio_webhook_authentication.rb:30:in `call'
bullet (5.9.0) lib/bullet/rack.rb:15:in `call'
remotipart (1.4.2) lib/remotipart/middleware.rb:32:in `call'
warden (1.2.8) lib/warden/manager.rb:36:in `block in call'
warden (1.2.8) lib/warden/manager.rb:34:in `catch'
warden (1.2.8) lib/warden/manager.rb:34:in `call'
rack (2.0.6) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.0.6) lib/rack/etag.rb:25:in `call'
rack (2.0.6) lib/rack/conditional_get.rb:38:in `call'
rack (2.0.6) lib/rack/head.rb:12:in `call'
actionpack (5.2.2) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
rack (2.0.6) lib/rack/session/abstract/id.rb:232:in `context'
rack (2.0.6) lib/rack/session/abstract/id.rb:226:in `call'
actionpack (5.2.2) lib/action_dispatch/middleware/cookies.rb:670:in `call'
activerecord (5.2.2) lib/active_record/migration.rb:559:in `call'
actionpack (5.2.2) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
activesupport (5.2.2) lib/active_support/callbacks.rb:98:in `run_callbacks'
actionpack (5.2.2) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (5.2.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.2) lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
web-console (3.7.0) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.7.0) lib/web_console/middleware.rb:30:in `block in call'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `catch'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `call'
actionpack (5.2.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.2) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.2) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.2) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.2) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.2) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.2) lib/rails/rack/logger.rb:26:in `call'
ahoy_matey (2.1.0) lib/ahoy/engine.rb:20:in `call_with_quiet_ahoy'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.2.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
request_store (1.4.1) lib/request_store/middleware.rb:19:in `call'
actionpack (5.2.2) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.0.6) lib/rack/method_override.rb:22:in `call'
rack (2.0.6) lib/rack/runtime.rb:22:in `call'
activesupport (5.2.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.2) lib/action_dispatch/middleware/static.rb:127:in `call'
rack (2.0.6) lib/rack/sendfile.rb:111:in `call'
sentry-raven (2.7.4) lib/raven/integrations/rack.rb:51:in `call'
webpacker (3.5.5) lib/webpacker/dev_server_proxy.rb:22:in `perform_request'
rack-proxy (0.6.5) lib/rack/proxy.rb:57:in `call'
railties (5.2.2) lib/rails/engine.rb:524:in `call'
puma (3.12.0) lib/puma/configuration.rb:225:in `call'
puma (3.12.0) lib/puma/server.rb:658:in `handle_request'
puma (3.12.0) lib/puma/server.rb:472:in `process_client'
puma (3.12.0) lib/puma/server.rb:332:in `block in run'
puma (3.12.0) lib/puma/thread_pool.rb:133:in `block in spawn_thread'
```

**Comment by philnash** [comment]
Thanks for the detailed breakdown of the issue you're seeing. I will look into this this week.

**Comment by philnash** [comment]
Hey @alexford,

I understand that the tests are way behind on Rails and Devise, and that is on the todo list to bring up, but I do have a demo application using Rails 5 and Devise 4.5 that seems to work for me. Could you run it yourself and see if it works and if there are any obvious differences with your app?

The repo is here: https://github.com/twilio/authy-devise-demo

Thanks!

**Comment by alexford** [comment]
Thanks for the reply @philnash—I'll check it out. For the moment I was able to do what I needed with just `authy-ruby` but I am going to need this soon!

**Comment by alexford** [comment]
Hey, that was fruitful! The demo app works great, until I add `request_from_forgery` to `ApplicationController` for CSRF protection. Then, it breaks just like mine when I try to log in, with an `ActionController::InvalidAuthenticityToken` error.

**Comment by philnash** [comment]
Good news! I've found the issue. It is buried in the [Devise README](https://github.com/plataformatec/devise/blob/master/README.md#controller-filters-and-helpers) where it says:

> For Rails 5, note that `protect_from_forgery` is no longer prepended to the `before_action` chain, so if you have set `authenticate_user` before `protect_from_forgery`, your request will result in "Can't verify CSRF token authenticity." To resolve this, either change the order in which you call them, or use `protect_from_forgery prepend: true`.

In the demo repo, I updated the application controller to:

```ruby
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception, prepend: true
end
```

and, after removing the second redirect test, which doesn't work anyway, your new test passed. I'll add this to the documentation here and comment across the other issues.

Thanks for your work digging into this.

**Comment by alexford** [comment]
You're right, that does fix it!

I had even tried that in my app, but was convinced didn't work. I looked back at the branch and lo and behold I had written `preprend` instead of `prepend` 🤦‍♂️ 

Thank you!

**Comment by philnash** [comment]
Oh no! I hate it when that happens!

Glad it's working now. Will update the docs today.
