### ISSUE TITLE
Forward reference to DeviseAuthy

### ISSUE THREAD

**Issue by petergoldstein** [twilio/authy-devise#111]
The addition of the line

    Authy.user_agent = "DeviseAuthy/#{DeviseAuthy::VERSION} - #{Authy.user_agent}"

in `lib/devise_authy.rb` leads to a fatal error on requiring DeviseAuthy.  This line references a module name that is not yet defined.  So when Bootsnap/Authy processes the user_agent, it causes an error.

An example stack trace is:

> Caused by:
> NameError: uninitialized constant DeviseAuthy
> /home/circleci/auth_manager/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/active_support.rb:58:in `block in load_missing_constant'
> /home/circleci/auth_manager/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/active_support.rb:16:in `allow_bootsnap_retry'
> /home/circleci/auth_manager/vendor/bundle/ruby/2.5.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/active_support.rb:57:in `load_missing_constant'
> /home/circleci/auth_manager/vendor/bundle/ruby/2.5.0/gems/devise-authy-1.11.0/lib/devise-authy.rb:6:in `<main>'

This line should either be removed entirely, or moved until after the actual definition of DeviseAuthy.

**Comment by philnash** [comment]
Oh man, I apologise for this. I don't know why the tests didn't pick this up. Will look into that.

Anyway, I just release version 1.11.1 that fixes this. Please try again with the latest version and let me know how you go.

**Comment by petergoldstein** [comment]
@philnash Version 1.11.1 looks good, thanks.
