### ISSUE TITLE
devise_authy.js is out of date and doesn't work

### ISSUE THREAD

**Issue by philnash** [twilio/authy-devise#142]
[devise_authy.js](https://github.com/twilio/authy-devise/blob/master/app/assets/javascripts/devise_authy.js) relies on JQuery and jquery-ujs which was moved out of Rails since version 5.1.

We should rewrite this to work with rails-ujs (or investigate removing it entirely).

**Comment by winstonwolff** [comment]
I'm having this problem too. When a user taps "Get the code sent to you via text message" on the "Get Authy Code" page, they get zero feedback.

One could rewrite devise_auth.js it initiates the server request and handles the response, instead of relying on UJS to initiate the request and then binding to 'ajax:success' to handle the response.

**Comment by philnash** [comment]
**This library is no longer actively maintained.** The Authy API has been replaced with the [Twilio Verify API](https://www.twilio.com/docs/verify). Twilio will support the Authy API through November 1, 2022 for SMS/Voice. After this date, we’ll start to deprecate the service for SMS/Voice. Any requests sent to the API after May 1, 2023, will automatically receive an error.  Push and TOTP will continue to be supported through July 2023.

[Learn more about migrating from Authy to Verify.](https://www.twilio.com/blog/migrate-authy-to-verify)

Please visit the Twilio Docs for:
* [Verify + Ruby (Rails) quickstart](https://www.twilio.com/docs/verify/quickstarts/ruby-rails)
* [Twilio Ruby helper library](https://www.twilio.com/docs/libraries/ruby)
* [Verify API reference](https://www.twilio.com/docs/verify/api)
* **Coming soon**: Look out for a new Devise plugin to use Twilio Verify with Devise

Please direct any questions to [Twilio Support](https://support.twilio.com/hc/en-us). Thank you!
