### ISSUE TITLE
AUTHY-WITH-QR-CODE

### ISSUE THREAD

**Issue by thisaliahmad** [twilio/authy-devise#147]
I am working on authy-devise with the user, and active admin both, I want the user to on two-factor authentication with QR code. it's showing my error undefined qr_code when I enter config.authy_enable_qr_code = true  in devise.rb. and how i will get QR code in html on my custom view. help needed!

**Comment by philnash** [comment]
Have you enabled _Generic authenticator tokens_ in your Authy Application settings in [the Twilio console](https://www.twilio.com/console/authy/applications)? What version of authy-devise are you using?

In a custom view you should have access to a `@authy_qr_code` instance variable that contains the URL to a QR code image.

**Comment by thisaliahmad** [comment]
yes, my QR is enabled on Twilio! am using devise-authy (2.2.0) gem and when I use @authy_qr_code its show me the error of undefined, as config.authy_enable_qr_code = true in devise.rb also generates Error.

**Comment by philnash** [comment]
What is the error that you see generated when you enable `config.authy_enable_qr_code = true`? Can you paste the stack trace here, please?

**Comment by philnash** [comment]
I just created an ActiveAdmin application with DeviseAuthy and turned QR codes on in `devise.rb` and it worked for me.

I was seeing errors when I did not have _Generic authenticator tokens_ enabled for my Authy application.

Can you double check that for the Authy application that you are working with (that you have the API key for) that _Generic authenticator tokens_ are enabled in the settings. Note: once you flip the switch in the settings, you need to save the application, otherwise it won't be saved.

**Comment by thisaliahmad** [comment]
I got it, the issue was with my Twillio api key. now QR link is creating. can you give me any lead how can I hit the link first and get the QR image in my rails application rather than clicking on the link and than going to another tab? thank-you

**Comment by thisaliahmad** [comment]
if you upload your application where you integrate authy with active admin it will be great help for me to learn it.

**Comment by thisaliahmad** [comment]
I have to save country code and phone numbers in my database, I applied two-factor-authentication from them, for that, I over-ride the POST_enable_authy method with superclass  Devise::DeviseAuthyController for both admin_users and users now am getting the error of superclass mismatch any solution for this?

**Comment by philnash** [comment]
Can you post the full stack trace please? I will try to replicate.

**Comment by philnash** [comment]
Hey @thisaliahmad, can you share the stack trace so I can see what's going on here? Thanks!

**Comment by philnash** [comment]
I'm going to close this issue, but if you're still having issues, please re-open it with more details.

Thanks!
