### ISSUE TITLE
POST_disable_authy action does not clear the session["#{resource_name}_authy_token_checked"] variable

### ISSUE THREAD

**Issue by RoseAndres** [twilio/authy-devise#148]
I have parts of my layout views that are dependent on 2FA having been passed (which can be checked via the value of `session["#{resource_name}_authy_token_checked"]`, which is set via `record_authy_authentication` in `helpers.rb`). 

When I logged in as a User and verified with 2FA, then clicked a button that would POST to the disable_authy_path for my resource, it did not reset the session variable (`session[:user_authy_token_checked]` in my case). I checked the code for the `POST_disable_authy` action in `devise_authy_controller.rb` to verify and saw that there is no logic to clear this.

I will work on submitting a PR for a fix in the next day or so.

**Comment by philnash** [comment]
**This library is no longer actively maintained.** The Authy API has been replaced with the [Twilio Verify API](https://www.twilio.com/docs/verify). Twilio will support the Authy API through November 1, 2022 for SMS/Voice. After this date, we’ll start to deprecate the service for SMS/Voice. Any requests sent to the API after May 1, 2023, will automatically receive an error.  Push and TOTP will continue to be supported through July 2023.

[Learn more about migrating from Authy to Verify.](https://www.twilio.com/blog/migrate-authy-to-verify)

Please visit the Twilio Docs for:
* [Verify + Ruby (Rails) quickstart](https://www.twilio.com/docs/verify/quickstarts/ruby-rails)
* [Twilio Ruby helper library](https://www.twilio.com/docs/libraries/ruby)
* [Verify API reference](https://www.twilio.com/docs/verify/api)
* **Coming soon**: Look out for a new Devise plugin to use Twilio Verify with Devise

Please direct any questions to [Twilio Support](https://support.twilio.com/hc/en-us). Thank you!
