### ISSUE TITLE
2.2.1 on rubygems

### ISSUE THREAD

**Issue by biow0lf** [twilio/authy-devise#150]
Hi,

I see new version on rubygems (2.2.1) and don't see commits for this version and tag.

I make diff to make sure that this is 2.2.1 release and its looks good.

Please, push commits and tag

Thank you!

**Comment by philnash** [comment]
Apologies, I push to my own fork and this main repo and I forgot to push to this repo this time. I've pushed all the commits now. Thanks for the heads up!
