### ISSUE TITLE
POST_enable_authy redirects back to the same page

### ISSUE THREAD

**Issue by diegopolido** [twilio/authy-devise#158]
Seems the `Authy::API.register_user` method doesn't fetch the user and redirects back to the same page (to fill the phone again)

I tried to run on rails console, but it returns a blank object:

```
    @authy_user = Authy::API.register_user(
      :email => "my-valid@email.com",
      :cellphone => "myvalidnumber",
      :country_code => "validcountrycode"
    )
    
    => {}
```

What should I do?

**Comment by philnash** [comment]
I have dropped an answer on [authy-ruby#71](https://github.com/twilio/authy-ruby/issues/71), hopefully it helps!

**Comment by philnash** [comment]
**This library is no longer actively maintained.** The Authy API has been replaced with the [Twilio Verify API](https://www.twilio.com/docs/verify). Twilio will support the Authy API through November 1, 2022 for SMS/Voice. After this date, we’ll start to deprecate the service for SMS/Voice. Any requests sent to the API after May 1, 2023, will automatically receive an error.  Push and TOTP will continue to be supported through July 2023.

[Learn more about migrating from Authy to Verify.](https://www.twilio.com/blog/migrate-authy-to-verify)

Please visit the Twilio Docs for:
* [Verify + Ruby (Rails) quickstart](https://www.twilio.com/docs/verify/quickstarts/ruby-rails)
* [Twilio Ruby helper library](https://www.twilio.com/docs/libraries/ruby)
* [Verify API reference](https://www.twilio.com/docs/verify/api)
* **Coming soon**: Look out for a new Devise plugin to use Twilio Verify with Devise

Please direct any questions to [Twilio Support](https://support.twilio.com/hc/en-us). Thank you!
