### ISSUE TITLE
Verify API?

### ISSUE THREAD

**Issue by earnold** [twilio/authy-devise#160]
Hi there,

When I follow the link to [Two-Factor Authentication with Authy](https://www.twilio.com/docs/authy) I see the following message: 

> For new development, we encourage you to use the Verify API instead of the Authy API. The Verify API is an evolution of the Authy API with continued support for SMS, voice, and email one-time passcodes, an improved developer experience...

Should I understand that to mean that I should note use this gem a new project? I see that Twilio is the sponsor of this gem, so I was a little big confused. 

Thanks in advance for any clarification!

**Comment by philnash** [comment]
Hey @earnold, thanks for the question. Both the Authy APIs and Twilio Verfiy are Twilio products and you are right that we  are now recommending Twilio Verify for new projects. I'll be honest, I've had "build a `twilio-verify-devise` plugin" on my to do list for a while now and have not had the chance to get around to it yet.

On the other hand, there is currently no end of life for the Authy APIs though, so you can still use this gem. Also, if you are looking for support for app based OTPs, the Authy APIs are currently the only way to achieve that. So, it is up to you what you choose to use, but Twilio Verify will be the API that continues to evolve from this point.

**Comment by earnold** [comment]
@philnash Thanks for the comprehensive answer! Much appreciated.
