### ISSUE TITLE
Why doesn't my app show up in Authy on my cellphone

### ISSUE THREAD

**Issue by betjaminrichards** [twilio/authy-devise#19]
I have gem installed and configured in my application as per the read me.

I can verify with tokens sent to me by SMS. However, my app never appears in the list of apps set up for my Authy account on my mobile.

Am I missing some configuration issue?

**Comment by daniel3zhang** [comment]
If I reinstall the app, the existing account will be lost. Is there any way to migrate my existing Authy account to other Authy devices?
