### ISSUE TITLE
authy-devise adds a  call to `warden.authenticate?` before all application actions

### ISSUE THREAD

**Issue by jcmorrow** [twilio/authy-devise#76]
In a recent project I have two classes of users, one who signs in only via an API (users) and one who signs in via a browser (admins). I had stopped `warden` from storing `current_user`s in the session, but adding `authy-devise`, even though it was only added for admins, still broke this. It's because https://github.com/authy/authy-devise/blob/87731bec3e6bd5ecd84aa174bacec15da1f24687/lib/devise-authy/rails.rb does:

```
    ActiveSupport.on_load(:action_controller) do
      include DeviseAuthy::Controllers::Helpers
    end
```

and that calls 
```
included do
  before_action :check_request_and_redirect_to_verify_token, :if => :is_signing_in?
end
```

and `:is_signing_in?` calls the devise helper `signed_in?` which will authenticate with warden and store it in the session 😞 

This is a pain point in devise that is not unique to this gem, but could we solve some of it in this scenario by removing the attempt to verify in the following method?

```
      def is_signing_in?
        if devise_controller? && signed_in?(resource_name) &&
          is_devise_sessions_controller? &&
          self.action_name == "create"
          return true
        end

        return false
      end
```

It seems like it should be unnecessary since `check_request_and_redirect_to_verify_token` is implemented as:

```
      def check_request_and_redirect_to_verify_token
        if signed_in?(resource_name) &&
           warden.session(resource_name)[:with_authy_authentication] &&
           require_token?
          # login with 2fa
          id = warden.session(resource_name)[:id]

          remember_me = (params.fetch(resource_name, {})[:remember_me].to_s == "1")
          return_to = session["#{resource_name}_return_to"]
          sign_out

          session["#{resource_name}_id"] = id
          # this is safe to put in the session because the cookie is signed
          session["#{resource_name}_password_checked"] = true
          session["#{resource_name}_remember_me"] = remember_me
          session["#{resource_name}_return_to"] = return_to if return_to

          redirect_to verify_authy_path_for(resource_name)
          return
        end
      end
```

FWIW, I personally got around this by implementing the following in my `ApplicationController`:

```
  def is_signing_in?
    if request.format.json?
      false
    else
      super
    end
  end
```

YMMV.

**Comment by philnash** [comment]
Hi!

I know this issue is from a long time ago, but I took over maintaining the library a couple of months ago and I want to address all the open issues.

I understand that you fixed this for yourself by over-riding `is_signing_in?` but I wanted to understand the overall issue.

Is it that `signed_in?(resource_name)` is called twice, in both the guard `is_signing_in?` and the `before_action` `check_request_and_redirect_to_verify_token`?

In your case, would `is_signing_in?` shortcut out for one of the other conditionals; `devise_controller?`, `is_devise_sessions_controller?` or `self.action_name == "create"`?

So, would removing `signed_in?(resource_name)` from `is_signing_in?`, but keeping it as part of `check_request_and_redirect_to_verify_token` fix this for you and allow you to remove your own defined `is_signing_in?`?

Thanks!

**Comment by jcmorrow** [comment]
Hey, I appreciate you addressing this. I haven't dealt with this project/devise since around the time I raised this issue, so my instinct might be off, but I *believe* you hit upon what my preferred solution was - don't called `signed_in?` in `is_signing_in?`. If that causes other issues elsewhere I have no idea, but it made sense to me at the time 😄 

Again, thanks for maintaining this, let me know if I can add anything else!

**Comment by philnash** [comment]
I think you're right, just wanted to make sure too! Will try to get this fix into the library when I find a bit of time.

I don't know if it'd be possible, but would be great if you were able to test the updated version within your app? I don't have anything set up that doesn't expect `current_user` to be set for part of the app.
