### ISSUE TITLE
Generated migration not completely compatible for rails 5+ apps

### ISSUE THREAD

**Issue by lancecarlson** [twilio/authy-devise#89]
The migration that is generated inherits from ActiveRecord::Migration instead of ActiveRecord::Migration[5.2].

Here is the error I get:

```
$ rake db:migrate
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class DeviseAuthyAddToCredentials < ActiveRecord::Migration[4.2]
```
Easy fix on my end, but maybe the edge version should support rails 5.2?

**Comment by DannyBen** [comment]
Why is this issue closed? I am facing the same issue now.
Generated migrations use this syntax:

```ruby
class DeviseAuthyAddToUsers < ActiveRecord::Migration
```

Which then trigger this error:

```
$ bin/rails db:migrate
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

Directly inheriting from ActiveRecord::Migration is not supported. Please specif
y the Rails release the migration was written for:
```

Using rails 6.0.2.2

**Comment by philnash** [comment]
@DannyBen I thought I'd fixed it. It should generate a migration with the correct version (based on [this code](https://github.com/twilio/authy-devise/blob/master/lib/generators/active_record/devise_authy_generator.rb#L18-L20)). What version of `devise-authy` are you using?

**Comment by DannyBen** [comment]
Hmm... I am using the latest version 1.11.1.
Not sure what happened, but I definitely had to add the `[6.0]`.

**Comment by philnash** [comment]
I'll open this back up and have a look through. Sorry this didn't work for you.

**Comment by philnash** [comment]
Found the problem! The initial fix for this checked that the Rails version was version 5. There has been an update to check that the version is 5 or greater, but that has not been released yet. Sorry!

Will work towards a release this week that brings this all up to date.

**Comment by philnash** [comment]
@DannyBen I have pushed the latest as version 2.0.0 (major bump because of updates to devise/rails dependencies, which probably don't affect your codebase these days). But this should work now.

**Comment by DannyBen** [comment]
Excellent! Thanks for the quick fix.
