### ISSUE TITLE
Install docs for existing user models don't create migration

### ISSUE THREAD

**Issue by cschneid** [twilio/authy-devise#96]
I have an existing devise powered app, and am adding authy. Following the instructions in the readme: 

```
Configure your Devise user model:

rails g devise_authy [MODEL_NAME]

or add the following line to your User model

devise :authy_authenticatable, :database_authenticatable
```

I did the second, adding `:authy_authenticatable`. 

But the `rails g devise_authy User` has the side effect of also creating the migration needed.

This is probably just a doc issue, but I'm not sure what the recommended approach is to get that migration.

**Comment by philnash** [comment]
Thanks for the report. I'll add the documentation for the migration now.
